### ISSUE TITLE
Todo / Roadmap

### ISSUE THREAD

**Issue by lahmatiy** [discoveryjs/cpupro#1]
## Input formats

- [x] Chromium Performance Profile
    - [ ] Extract additional events like compute styles, layout, compile code etc
- [x] [Edge Enhanced Performance Traces](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/share-traces) (.devtools)
- [x] V8 log preprocessed with `--preprocess`
    - [ ] Scripts
    - [ ] Function state transitions
- [ ] Raw V8 log
- [ ] ~Support for Firefox/Safari profiles~ Postponed until done with V8

## Integrations

- [ ] Integration with playwright (using [context.tracing](https://playwright.dev/docs/api/class-tracing)?)
- [ ] Integration with puppeteer (using [page.tracing](https://github.com/puppeteer/puppeteer/blob/v13.2.0/docs/api.md#class-tracing)?)
- [ ] Viewer as PWA
- [ ] [File Handling](https://web.dev/file-handling/)

## API

- [ ] Marks (smth like `performance.mark()` / `performance.measure()`)
- [ ] `setSamplingInterval`
- [ ] `cpupro -- script.js ...params` as an alternative to `node --require cpupro script.js ...params`

## Data (capturing & processing)

- [x] Fix total time computation
- [x] Bring `file:///path/...` and `/path/...` to one form
- [ ] Exclude `startProfiling`/`stopProfiling` frames from the profile
- [x] Attach RegExp location to a parent call frame
- [ ] ~Populate collected profile with code fragments~ This data can be obtained from V8 log

## Viewer

- [ ] Switch between threads (for Chromium timeline profiles with multiple threads)
- [ ] Marks on timelines
- [ ] Flow view
- [ ] Tree with columns view
- [ ] Keyboard navigation in trees / tables
- [x] Flame charts
- [x] Example data
- [ ] Instructions how to capture profile file

**Comment by cmdcolin** [comment]
great work on this! can the app display webworker traces also? just an idea

**Comment by lahmatiy** [comment]
@cmdcolin I'm going to add a switching between threads for Chromium timeline profiles (added a point to "viewer" about it), since a webworker is a thread and timeline contains a separate profile for each of them. However, that's a complex task and I can't currently say for sure about ETA of this feature.

**Comment by eJayYoung** [comment]
will it support heap profile or gc trace as well，I really like this kind of rethink about XXX profile analysis
